### ISSUE TITLE
In-plot time display

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1258]
We have an existing Issue for a "heads-up" style display that puts an RCP view over the plot ( #1250).  

An alternate suggestion is to show the current time on the plot - similar to the scale object.

This element would have these requirements:

## Creation
* **[UPDATED]** We will add "Time Display (Absolute)" and "Time Display (Relative)" elements to the Chart Features toolbar.  The java objects would be called TimeDisplayPainterAbsolute and TimeDisplayPainterRelative.
* **[UPDATED]** When creating a TimeDisplayPainterRelative class, the current TimeController time will be used as the Origin value.
* Multiple instances of the Time Display may be added by the user, which may be positioned in different locations
* The Time Display entries will be shown under the "Chart Features" layer.
* **[UPDATED]** We will need new icons for these Time Display elements.

## Display
* The Time Display element will be shown on the plot, and get updated each time the time changes.
* All of the time location elements at each location (br,br,tl,tr) will be shown in one line, separated by "|" characters.

## Properties
Users will be able to format:
* Text location (bl, br, tl, tr).
* **[UPDATED]** Font (including Font size)
* Text Color
* **[UPDATED]** Background color
* **[UPDATED]** Filled Background (yes/no)
* Name
* Text font
* Text prefix (label)
* Text suffix (label)
* **[UPDATED]**  Time Origin for TimeDisplayPainterRelative. Time Display will show the offset from that time (-10 secs,  +1.5 minutes, +2:20:12).
* **[UPDATED]**  DTG format: Absolute and Relative modes will each have their own set of format values.  Absolute times will come from MyDateFormatPropertyEditor. Relative times from a custom list within the TimeDisplayPainterRelative class.  ("Millis", "Secs", "Mins", "Hours", "Days"). 
* **[UPDATED 2]** We should provide a -ve color option for relative times, to make +/- more clear
* **[UPDATED 2]** We should provide a semi-transparent fill option, to make the background fill semi-transparent.

**Comment by IanMayo** [comment]
@pecko - I think the requirements for this may require some more tidying.  But, I think it's ready for you to work on the underlying logic / control flows.

**Comment by pecko** [comment]
I will check this issue after solving #1203.

**Comment by pecko** [comment]
Base steps: https://github.com/pecko/debrief/commit/dc0183e5ed028d86b8ad6ac68ed2443460482f37

**Comment by IanMayo** [comment]
First steps looking good - thanks.

**Comment by pecko** [comment]
> All of the time location elements at each location (br,br,tl,tr) will be shown in one line, separated by "|" characters.

Could you send an example (just formatting)?

> Text size

We can calculate the widget size based on font and formatted string. What this value will control?

**Comment by pecko** [comment]
I have added base painting:

![image](https://cloud.githubusercontent.com/assets/534584/8140795/607ccb32-115f-11e5-8820-58e4675db180.png)

**Comment by pecko** [comment]
more painting...

![image](https://cloud.githubusercontent.com/assets/534584/8145278/c4a5830e-1201-11e5-915f-79fafd74a6ea.png)

**Comment by IanMayo** [comment]
ok, ok, let's not go over the top :-)  I think you can pause this issue until I've had a good chance to review it on Monday.

**Comment by pecko** [comment]
I will just add formatting and persistence.

**Comment by IanMayo** [comment]
sure, ok

Ian Mayo
Deep Blue C Technology Ltd
- New technologies, implemented well

**Comment by pecko** [comment]
I have added simple formatting (similar to the time controller view) and persistence.
Formatting needs some enhancement, but I expect your feedback here.

RE persistence - there are the following issue:
- add a time display
- save a plot
- exit Eclipse without closing plot
- start Eclipse
- the time display will not be shown

I will try to solve that tomorrow. Workaround is close/open the plot.

**Comment by pecko** [comment]
The issue when starting Eclipse described above is fixed.

TODO (after @IanMayo's  review)
- polishing (formatting, painting ...)
- add time display to plot xsd schema
- fixing bugs

**Comment by IanMayo** [comment]
Hi there Peco - thanks for this, it's working well.

I've added some tidier requirements to the issue, marked with **[UPDATED]**.

There's also one slight change - the Time Display elements should be added to the *Chart Features* layer when they're created.

**Comment by pecko** [comment]
> There's also one slight change - the Time Display elements should be added to the Chart Features layer when they're created.

This is tricky. I have done it firstly, but I couldn't solve persistence because the following;

- time display depends on plot editor (or at least time controller) for time
- we can inject layer's children to persistence, than only root layer

Because of that I implement it as root layer.
If we want too add it to the Chart Features,, we will have to probably implement a new extension point for this.

> [UPDATED] When creating a TimeDisplayPainterRelative class, the current TimeController time will be used as the Origin value.

You mean start origin value which the user can change. Right?
time display value would be difference between entered origin value and the current Time Controller time.

**Comment by IanMayo** [comment]
1. Root layer.  We can't have the TimeDisplay objects at the top layer - the Outline View will just be too cluttered.  It's ok to create a new extension point, if we must.

2. Yes, the origin time can be edited.  But, to start off with it takes the current TimeController time.  The time displayed will be the difference, like:  "-5 seconds", "+12 minutes", etc.

**Comment by pecko** [comment]
> Root layer. We can't have the TimeDisplay objects at the top layer - the Outline View will just be too cluttered. It's ok to create a new extension point, if we must.

I will try to implement it in the easiest way.

> Yes, the origin time can be edited. But, to start off with it takes the current TimeController time. The time displayed will be the difference, like: "-5 seconds", "+12 minutes", etc.

I hope, I understand.

**Comment by IanMayo** [comment]
> I will try to implement it in the easiest way.

Sure, good news.  

I've just done some code hunting.  I found our use of MovingPlottable in PlotEditor.java:1323  

I guess we could mark our TimeDisplayPainters as MovingPlottable, then in PlotEditor.paintThisLayer, search through the current layer for MovingPlottable objects, then paint them with paint(dest, tNow).

**Comment by pecko** [comment]
Thanks. It helps.

**Comment by pecko** [comment]
I have implemented TimeDisplayPainter as MovingPlottable. The time display painter has moved to the Chart Features layer.

Disadvantages: The Chart features layer can't be double buffered.

TODO
- implement absolute and relative painters
- adjust plot xml schema

**Comment by IanMayo** [comment]
Oh, we don't want to lose double-buffering.

How about if we create a "Dynamic features" top level layer?

**Comment by pecko** [comment]
> How about if we create a "Dynamic features" top level layer?

OK.

**Comment by pecko** [comment]
> How about if we create a "Dynamic features" top level layer?

I have done it.

**Comment by IanMayo** [comment]
Thanks for the updates, I'm having a play now.  Feedback:
* the styling should be "roughly" like the Scale.  
* the positioning should allow the scale to still be placed in that corner (so we can have both time display and scale in each corner)
* if I remove the "filled background", then the previous text isn't replaced - it turns into a blur
* could you make the background transparent by default?  Then it will "blend in" more with the scale control.

**Comment by pecko** [comment]
> the styling should be "roughly" like the Scale.

Not sure what you mean 

> if I remove the "filled background", then the previous text isn't replaced - it turns into a blur

I can't reproduce it. 
When you set "Fill background" then TimeDisplayPainter fill a rectangle with background color about text, otherwise it will not fill rectangle. In any case the text is painted in the same way.
Could you, please, create some screenshot?

> could you make the background transparent by default? Then it will "blend in" more with the scale control.

It means "Fill Background" = no. Right?

**Comment by IanMayo** [comment]
> "Roughly like the scale"

By default the time display should be in a similar font/style/color as the default for the scale.   Here's the scale:
![stylewithscale](https://cloud.githubusercontent.com/assets/1108513/8256674/6e0ad21c-16a0-11e5-9d75-d1d6402f7348.png)

> "up" and "down"
The time display should sit "above" the scale bar (when at the bottom), or "below" the scale (when at the top).  When it's next to the scale bar they should neatly match each other.

> "filled background"

Here is the Time Display when I set Fill Background to False:
![nofillbackground](https://cloud.githubusercontent.com/assets/1108513/8256685/7ed51b84-16a0-11e5-81f0-ef757e1df529.png)

That's fine. But, when I move the time slider, the new time values over-write the previous ones:
![timeoverwriting](https://cloud.githubusercontent.com/assets/1108513/8256700/8a282350-16a0-11e5-8972-aeec02d9d73c.png)

> It means "Fill Background" = no. Right?

Yes.

**Comment by pecko** [comment]
I have added relative painter and solve some your suggestions.

Notice:

- repainting with no filling background doesn't work yet; trying to fix it
- relative formatting is rough for now (just simple number)
- placement 
  Time display can't be send left (or right) to scale because scale and time display class don't know width (string size, font size ...) each other. 
I have set time display above (bottom) or below (top) of scale

**Comment by pecko** [comment]
screencast:

![image](https://cloud.githubusercontent.com/assets/534584/8262598/ab765f4e-16d3-11e5-8d3e-e422c5190181.png)

**Comment by pecko** [comment]
> repainting with no filling background doesn't work yet; trying to fix it

Fixed

**Comment by IanMayo** [comment]
Relative time formatting:  

I did like the formatting strategy (if/else ladder) provided in [this](http://www.blackwasp.co.uk/RelativeTime.aspx) article.

But, initially, I think a better strategy would be to format it as hh:mm:ss, with a + or a - at the front.

Also, initially, I suggest that -ve values are plotted in Red text, then it's extra-clear about +ve/-ve.  But, this would require an extra property editor.

Note: the TimeDisplayPainterInfo object could examine if "relative" is true or not, then decide whether to add an extra "negative color" property.  The -ve color property would be ignore for +ve relative time values.

**Comment by IanMayo** [comment]
Oh, and @pecko  - the prefix/suffix is currently being ignored for the Relative time display.  

FIXED :-)

**Comment by IanMayo** [comment]
@pecko - I'm afraid the current background fill strategy still isn't acceptable. It fails when we switch on Natural Earth.

Somehow, we do need to make it transparent  (like we do for the time highlight rectangle that moves up/down tracks with time, and the new dynamic shapes).

**Comment by pecko** [comment]
I have added the negative color property and +/-hh:mm:ss formatting for relative time.

**Comment by pecko** [comment]
> if I remove the "filled background", then the previous text isn't replaced - it turns into a blur

Fixed.

**Comment by pecko** [comment]
I have added the timeDisplay element to the plot xsd schema and fixed some schema issue.
Now, I waiting your suggestion for this issue.

**Comment by pecko** [comment]
@IanMayo comment from the PR:

@pecko - we have "special handling" that means the time display objects have to be in a "DynamicLayer" object. So, we need to prevent these objects from being moved/pasted into a layer that isn't a DynamicLayer.

We need to do this in code.

We also need to prevent this happening in the XML file. So, instead of having a layer that has a boolean "MovingLayer" attribute, I think we should declare a DynamicLayer type in XML, extending the Layer object. Only this object should allow timeDisplay objects within it.

**Comment by pecko** [comment]
Second @IanMayo comment:

@pecko - we need some more tidying to the relative time formats.

In relative mode, the time format string is being ignored. I think the list needs to include these options:

Secs
Mins
Hours
Days
HH:mm:ss
yy/MM/dd HH:mm:ss
The first four formats would all be formatted as integers.

**Comment by pecko** [comment]
@IanMayo  I have implemented your suggestions related to xml (xsd) and relative time format. Please review.

**Comment by IanMayo** [comment]
good work - have added some inline comments. I think we still need to prevent a user from moving a TimeDisplay object to a different type of layer, within Debrief itself.

Maybe TimeDisplayPainter could implement a NotInBaseLayer marker interface.  When Plottables.add() is called - it could check for this marker, and throw an error if present?

**Comment by pecko** [comment]
I will implement it shortly.

**Comment by pecko** [comment]
Done!

**Comment by pecko** [comment]
@IanMayo commented to PR:

> Unfortunately, to be able to create a TimeDisplay, our DynamicLayer needs to have its own "Add" 
> method - to over-ride the BaseLayer implementation. The current implementation won't allow a 
> TimeDisplay to be added.

> Surely you tested the new functionality before you committed it? ;-)

I was sure that I'm. Check again ...

**Comment by pecko** [comment]
@IanMayo You are right. Seems I haven't tested my latest commit :(
Anyway, it is fine in master. You fixed that.

**Comment by IanMayo** [comment]
@pecko - was just about to close this, but spotted something.

Do the time display painters offer a "semi transparent background" option?

**Comment by pecko** [comment]
No, it doesn't. Will implement that.

**Comment by pecko** [comment]
The PR which adds semi transparent property: https://github.com/debrief/debrief/pull/1286

**Comment by IanMayo** [comment]
Closed in #1286

**Comment by IanMayo** [comment]
I don't think this feature is included in the User Guide. 

I don't know if it should go into the Tutorial, it's just a minor feature.

Assigning to Russ - so it can get into the User Guide.

**Comment by IanMayo** [comment]
Done.
